import React from "react";
import {
  Download,
  FileText,
  Plus,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function ReportsPage() {
  const reports = [
    {
      id: "rep-001",
      title: "Q2 2026 Financial Summary",
      period: "Q2 2026",
      generated: "Aug 18, 2026",
      size: "4.2 MB",
      format: "PDF",
      status: "Finalized",
      badgeVariant: "success" as const,
    },
    {
      id: "rep-002",
      title: "Monthly Sales by Channel",
      period: "July 2026",
      generated: "Aug 01, 2026",
      size: "1.8 MB",
      format: "CSV",
      status: "Verified",
      badgeVariant: "success" as const,
    },
    {
      id: "rep-003",
      title: "Inventory Valuation & Costs",
      period: "July 2026",
      generated: "Aug 01, 2026",
      size: "890 KB",
      format: "PDF",
      status: "Draft",
      badgeVariant: "secondary" as const,
    },
    {
      id: "rep-004",
      title: "Annual Revenue Growth Analysis",
      period: "Annual 2025",
      generated: "Jan 15, 2026",
      size: "12.4 MB",
      format: "PDF",
      status: "Finalized",
      badgeVariant: "success" as const,
    },
  ];

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-foreground sm:text-2xl">
            Financial & Operational Reports
          </h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            Generated summaries, accounting exports, and custom BI reports.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button size="sm" className="gap-1.5 text-xs">
            <Plus className="size-3.5" />
            <span>Generate Report</span>
          </Button>
        </div>
      </div>

      {/* Reports Table */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle className="text-sm font-semibold">
              Archived & Scheduled Reports
            </CardTitle>
            <CardDescription>
              Export-ready documents generated by Nexa BI
            </CardDescription>
          </div>
          <Badge variant="outline" size="sm">
            4 Documents
          </Badge>
        </CardHeader>

        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-y border-border bg-muted/20 text-muted-foreground">
                  <th className="py-2.5 px-4 font-medium">Report Name</th>
                  <th className="py-2.5 px-4 font-medium hidden sm:table-cell">Period</th>
                  <th className="py-2.5 px-4 font-medium">Status</th>
                  <th className="py-2.5 px-4 font-medium hidden md:table-cell">File Size</th>
                  <th className="py-2.5 px-4 font-medium text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/60">
                {reports.map((report) => (
                  <tr key={report.id} className="hover:bg-muted/30 transition-colors">
                    <td className="py-3 px-4">
                      <div className="font-semibold text-foreground flex items-center gap-2">
                        <FileText className="size-3.5 text-muted-foreground" />
                        <span>{report.title}</span>
                      </div>
                      <span className="font-mono text-[10px] text-muted-foreground">
                        Generated {report.generated} • {report.format}
                      </span>
                    </td>
                    <td className="py-3 px-4 font-mono text-muted-foreground hidden sm:table-cell">
                      {report.period}
                    </td>
                    <td className="py-3 px-4">
                      <Badge variant={report.badgeVariant} size="sm">
                        {report.status}
                      </Badge>
                    </td>
                    <td className="py-3 px-4 font-mono text-muted-foreground hidden md:table-cell">
                      {report.size}
                    </td>
                    <td className="py-3 px-4 text-right">
                      <Button variant="outline" size="xs" className="gap-1 font-mono text-[11px]">
                        <Download className="size-3" />
                        <span>Download</span>
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
