import React from "react";
import {
  FileText,
} from "lucide-react";
import { ReportAddButton } from "@/components/dashboard/reports/report-add-button";
import { ReportRowActions } from "@/components/dashboard/reports/report-row-actions";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/server";

export default async function ReportsPage() {
  const supabase = await createClient();

  const { data: reportsData, error } = await supabase
    .from('reports')
    .select('id, title, period, file_size_bytes, format, status, generated_at')
    .order('generated_at', { ascending: false });

  const formatBytes = (bytes: number, decimals = 1) => {
    if (!+bytes) return '0 Bytes';
    const k = 1024;
    const dm = decimals < 0 ? 0 : decimals;
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
  };

  const reports = (reportsData || []).map((report) => {
    let badgeVariant: "success" | "warning" | "brand" | "secondary" = "secondary";
    if (report.status === "Finalized" || report.status === "Verified") badgeVariant = "success";
    else if (report.status === "Draft") badgeVariant = "secondary";
    else if (report.status === "Generating") badgeVariant = "brand";
    else if (report.status === "Failed") badgeVariant = "warning";

    const generatedDate = new Date(report.generated_at);
    // Use UTC date to avoid timezone issues shifting the date
    const generatedStr = new Date(generatedDate.getTime() + Math.abs(generatedDate.getTimezoneOffset() * 60000))
      .toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' });

    return {
      id: report.id,
      title: report.title,
      period: report.period,
      generated: generatedStr,
      size: formatBytes(report.file_size_bytes),
      format: report.format,
      status: report.status,
      badgeVariant: badgeVariant,
    };
  });

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-foreground sm:text-2xl">
            Financial & Operational Reports
          </h1>
          <p className="text-xs text-muted-foreground mt-0.5">
            Generated summaries, accounting exports, and custom BI reports.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <ReportAddButton />
        </div>
      </div>

      {/* Reports Table */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <CardTitle className="text-sm font-semibold">
              Archived & Scheduled Reports
            </CardTitle>
            <CardDescription>
              Export-ready documents generated by Nexa BI
            </CardDescription>
          </div>
          <Badge variant="outline" size="sm">
            {reports.length} Documents
          </Badge>
        </CardHeader>

        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-y border-border bg-muted/20 text-muted-foreground">
                  <th className="py-2.5 px-4 font-medium">Report Name</th>
                  <th className="py-2.5 px-4 font-medium hidden sm:table-cell">Period</th>
                  <th className="py-2.5 px-4 font-medium">Status</th>
                  <th className="py-2.5 px-4 font-medium hidden md:table-cell">File Size</th>
                  <th className="py-2.5 px-4 font-medium text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/60">
                {reports.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="py-16 text-center">
                      <div className="flex flex-col items-center justify-center space-y-3">
                        <FileText className="size-8 text-muted-foreground/30" />
                        <div className="space-y-1">
                          <p className="text-sm font-medium text-foreground">No reports generated</p>
                          <p className="text-xs text-muted-foreground max-w-[250px] mx-auto leading-relaxed">
                            Generate your first financial or operational report to see it archived here.
                          </p>
                        </div>
                        <div className="pt-2">
                          <ReportAddButton />
                        </div>
                      </div>
                    </td>
                  </tr>
                ) : (
                  reports.map((report) => (
                    <tr key={report.id} className="hover:bg-muted/30 transition-colors">
                      <td className="py-3 px-4">
                        <div className="font-semibold text-foreground flex items-center gap-2">
                          <FileText className="size-3.5 text-muted-foreground" />
                          <span>{report.title}</span>
                        </div>
                        <span className="font-mono text-[10px] text-muted-foreground">
                          Generated {report.generated} • {report.format}
                        </span>
                      </td>
                      <td className="py-3 px-4 font-mono text-muted-foreground hidden sm:table-cell">
                        {report.period}
                      </td>
                      <td className="py-3 px-4">
                        <Badge variant={report.badgeVariant} size="sm">
                          {report.status}
                        </Badge>
                      </td>
                      <td className="py-3 px-4 font-mono text-muted-foreground hidden md:table-cell">
                        {report.size}
                      </td>
                      <td className="py-3 px-4 text-right">
                        <ReportRowActions report={{
                          id: report.id,
                          title: report.title,
                          period: report.period,
                          format: report.format,
                          status: report.status
                        }} />
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
