"use client";

import React, { useState } from "react";
import { Search, FileText } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ReportAddButton } from "@/components/dashboard/reports/report-add-button";
import { ReportRowActions } from "@/components/dashboard/reports/report-row-actions";
import { Button } from "@/components/ui/button";

interface ReportData {
  id: string;
  title: string;
  period: string;
  generated: string;
  size: string;
  format: string;
  status: string;
  badgeVariant: "success" | "warning" | "brand" | "secondary" | "destructive";
}

export function ReportDirectory({ reports }: { reports: ReportData[] }) {
  const [query, setQuery] = useState("");
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;

  const filteredReports = reports.filter((report) => {
    if (!query) return true;
    const q = query.toLowerCase();
    // Reports filter by title + period
    return report.title.toLowerCase().includes(q) || report.period.toLowerCase().includes(q);
  });

  const totalPages = Math.ceil(filteredReports.length / pageSize);
  const paginatedReports = filteredReports.slice(
    (currentPage - 1) * pageSize,
    currentPage * pageSize
  );

  return (
    <Card>
      <CardHeader className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <CardTitle className="text-sm font-semibold">
            Archived & Scheduled Reports
          </CardTitle>
          <CardDescription>
            Export-ready documents generated by Nexa BI
          </CardDescription>
        </div>
        
        <div className="flex items-center gap-2">
          <Badge variant="outline" size="sm" className="hidden sm:inline-flex">
            {reports.length} Documents
          </Badge>
          <div className="relative w-full sm:w-64">
            <Search className="size-3.5 absolute left-2.5 top-2.5 text-muted-foreground" />
            <Input
              placeholder="Search reports or period..."
              className="pl-8 text-xs"
              value={query}
              onChange={(e) => {
                setQuery(e.target.value);
                setCurrentPage(1);
              }}
            />
          </div>
        </div>
      </CardHeader>

      <CardContent className="p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-y border-border bg-muted/20 text-muted-foreground">
                <th className="py-2.5 px-4 font-medium">Report Name</th>
                <th className="py-2.5 px-4 font-medium hidden sm:table-cell">Period</th>
                <th className="py-2.5 px-4 font-medium">Status</th>
                <th className="py-2.5 px-4 font-medium hidden md:table-cell">File Size</th>
                <th className="py-2.5 px-4 font-medium text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/60">
              {reports.length === 0 ? (
                <tr>
                  <td colSpan={5} className="py-16 text-center">
                    <div className="flex flex-col items-center justify-center space-y-3">
                      <FileText className="size-8 text-muted-foreground/30" />
                      <div className="space-y-1">
                        <p className="text-sm font-medium text-foreground">No reports generated</p>
                        <p className="text-xs text-muted-foreground max-w-[250px] mx-auto leading-relaxed">
                          Generate your first financial or operational report to see it archived here.
                        </p>
                      </div>
                      <div className="pt-2">
                        <ReportAddButton />
                      </div>
                    </div>
                  </td>
                </tr>
              ) : filteredReports.length === 0 ? (
                <tr>
                  <td colSpan={5} className="py-16 text-center text-muted-foreground">
                    No results for &quot;<span className="font-medium text-foreground">{query}</span>&quot;
                  </td>
                </tr>
              ) : (
                paginatedReports.map((report) => (
                  <tr key={report.id} className="hover:bg-muted/30 transition-colors">
                    <td className="py-3 px-4">
                      <div className="font-semibold text-foreground flex items-center gap-2">
                        <FileText className="size-3.5 text-muted-foreground" />
                        <span>{report.title}</span>
                      </div>
                      <span className="font-mono text-[10px] text-muted-foreground">
                        Generated {report.generated} • {report.format}
                      </span>
                    </td>
                    <td className="py-3 px-4 font-mono text-muted-foreground hidden sm:table-cell">
                      {report.period}
                    </td>
                    <td className="py-3 px-4">
                      <Badge variant={report.badgeVariant} size="sm">
                        {report.status}
                      </Badge>
                    </td>
                    <td className="py-3 px-4 font-mono text-muted-foreground hidden md:table-cell">
                      {report.size}
                    </td>
                    <td className="py-3 px-4 text-right">
                      <ReportRowActions report={{
                        id: report.id,
                        title: report.title,
                        period: report.period,
                        format: report.format,
                        status: report.status
                      }} />
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {totalPages > 1 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-border bg-muted/10">
            <div className="text-[11px] text-muted-foreground font-medium">
              Page {currentPage} of {totalPages}
            </div>
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                className="h-7 text-[11px]"
                onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                disabled={currentPage === 1}
              >
                Previous
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="h-7 text-[11px]"
                onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                disabled={currentPage === totalPages}
              >
                Next
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
